# Generated by Django 3.1.14 on 2022-10-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_project_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='resource_file',
            field=models.FileField(default=None, upload_to='media/'),
        ),
    ]
