# Generated by Django 3.1.14 on 2022-10-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_task_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='resource_file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
